/**
 * Dump the exact "contract" an AI agent reads over MCP — the tools/list payload
 * (every tool's name + description + input schema). This is what the reviewer
 * audited from. Regenerate anytime after editing lib/mcp/tools.ts.
 *
 * Run:  npx tsx --conditions react-server scripts/dump-contract.ts
 * (--conditions react-server satisfies the `server-only` imports tools.ts pulls.)
 */
import "dotenv/config";
import { writeFileSync } from "node:fs";
import { TOOL_DEFS } from "../lib/mcp/tools";

// 1) The verbatim JSON-RPC result of an MCP `tools/list` call.
const toolsList = { tools: TOOL_DEFS };
writeFileSync("docs/ai-contract.json", JSON.stringify(toolsList, null, 2));

// 2) A human-readable rendering of the same thing.
let md = "# The AI contract — what an agent reads over MCP\n\n";
md += "> Auto-generated by `scripts/dump-contract.ts` from `lib/mcp/tools.ts`. Do not hand-edit.\n\n";
md += `This is the exact payload of the MCP **\`tools/list\`** call: **${TOOL_DEFS.length} tools**, each with a name, a description, and a JSON input schema. An agent connecting to a project reads this plus the runtime **\`get_project_info\`** orientation blob (URLs, boundaries, delivery-API reference) — those two are the whole surface it plans against.\n\n`;
md += "## Tool index\n\n";
for (const t of TOOL_DEFS) md += `- \`${t.name}\`\n`;
md += "\n---\n\n";
for (const t of TOOL_DEFS) {
  md += `## \`${t.name}\`\n\n`;
  md += `${t.description}\n\n`;
  md += "**Input schema:**\n\n```json\n" + JSON.stringify(t.inputSchema, null, 2) + "\n```\n\n";
}
writeFileSync("docs/ai-contract.md", md);

console.log(`Wrote ${TOOL_DEFS.length} tools → docs/ai-contract.md + docs/ai-contract.json`);
process.exit(0);
